import { OhaengType, CheonganType, JijiType } from '@/type/basicType';

export const jiji: Record<
    JijiType,
    {
        hanja: string;
        number: number;
        startTime: string;
        endTime: string;
        element: OhaengType;
        eumyang: '양' | '음';
        isEumyangInverse: boolean;
        animal: string;
        jijanggan: CheonganType[];
        samjae: JijiType[];
    }
> = {
    자: {
        hanja: '子',
        number: 0,
        startTime: '23:00',
        endTime: '01:00',
        element: '수',
        eumyang: '양',
        isEumyangInverse: true,
        animal: '쥐',
        jijanggan: ['임', '계'],
        samjae: ['인', '묘', '진'],
    },
    축: {
        hanja: '丑',
        number: 1,
        startTime: '01:00',
        endTime: '03:00',
        element: '토',
        eumyang: '음',
        isEumyangInverse: false,
        animal: '소',
        jijanggan: ['계', '신', '기'],
        samjae: ['해', '자', '축'],
    },
    인: {
        hanja: '寅',
        number: 2,
        startTime: '03:00',
        endTime: '05:00',
        element: '목',
        eumyang: '양',
        isEumyangInverse: false,
        animal: '호랑이',
        jijanggan: ['무', '병', '갑'],
        samjae: ['신', '유', '술'],
    },
    묘: {
        hanja: '卯',
        number: 3,
        startTime: '05:00',
        endTime: '07:00',
        element: '목',
        eumyang: '음',
        isEumyangInverse: false,
        animal: '토끼',
        jijanggan: ['갑', '을'],
        samjae: ['사', '오', '미'],
    },
    진: {
        hanja: '辰',
        number: 4,
        startTime: '07:00',
        endTime: '09:00',
        element: '토',
        eumyang: '양',
        isEumyangInverse: false,
        animal: '용',
        jijanggan: ['을', '계', '무'],
        samjae: ['인', '묘', '진'],
    },
    사: {
        hanja: '巳',
        number: 5,
        startTime: '09:00',
        endTime: '11:00',
        element: '화',
        eumyang: '음',
        isEumyangInverse: true,
        animal: '뱀',
        jijanggan: ['무', '경', '병'],
        samjae: ['해', '자', '축'],
    },
    오: {
        hanja: '午',
        number: 6,
        startTime: '11:00',
        endTime: '13:00',
        element: '화',
        eumyang: '양',
        isEumyangInverse: true,
        animal: '말',
        jijanggan: ['병', '기', '정'],
        samjae: ['신', '유', '술'],
    },
    미: {
        hanja: '未',
        number: 7,
        startTime: '13:00',
        endTime: '15:00',
        element: '토',
        eumyang: '음',
        isEumyangInverse: false,
        animal: '양',
        jijanggan: ['정', '을', '기'],
        samjae: ['사', '오', '미'],
    },
    신: {
        hanja: '申',
        number: 8,
        startTime: '15:00',
        endTime: '17:00',
        element: '금',
        eumyang: '양',
        isEumyangInverse: false,
        animal: '원숭이',
        jijanggan: ['무', '임', '경'],
        samjae: ['인', '묘', '진'],
    },
    유: {
        hanja: '酉',
        number: 9,
        startTime: '17:00',
        endTime: '19:00',
        element: '금',
        eumyang: '음',
        isEumyangInverse: false,
        animal: '닭',
        jijanggan: ['경', '신'],
        samjae: ['해', '자', '축'],
    },
    술: {
        hanja: '戌',
        number: 10,
        startTime: '17:00',
        endTime: '21:00',
        element: '토',
        eumyang: '양',
        isEumyangInverse: false,
        animal: '개',
        jijanggan: ['신', '정', '무'],
        samjae: ['신', '유', '술'],
    },
    해: {
        hanja: '亥',
        number: 11,
        startTime: '21:00',
        endTime: '23:00',
        element: '수',
        eumyang: '음',
        isEumyangInverse: false,
        animal: '돼지',
        jijanggan: ['무', '갑', '임'],
        samjae: ['사', '오', '미'],
    },
};

/**
 * 방합: 월지를 포함하여 세개 모두 있는 경우
 *
 * 삼합:
 * 1. 세개 모두 있는 경우 (충 있으면 깨짐, 위치 상관 없음)
 * 2. 왕지를 포함하여 2개 있는 경우 반합
 *
 * 육합: 바로 붙어있는 경우 (충이 있으면 깨짐)
 *
 * 삼형:
 * 1. 세개 모두 있는 경우 (위치 상관 없음)
 * 2. 두개만 있는 경우 반형
 *
 * 파 / 해 : 1. 바로 붙어있는 경우
 */
export const jijiRelation: Record<
    JijiType,
    {
        type: '왕지' | '묘지' | '생지';
        yukhap: JijiType;
        yukhapName: string;
        yukhapElement: string;
        samhap: JijiType[];
        samhapElement: string;
        samhapWangji: JijiType;
        banghap: JijiType[];
        banghapElement: string;
        chung: JijiType;
        chungName: string;
        samhyung: JijiType[];
        hyung: JijiType | '';
        hyungName: string;
        pa: JijiType;
        paName: string;
        hae: JijiType;
        haeName: string;
    }
> = {
    자: {
        type: '왕지',
        yukhap: '축',
        yukhapName: '자축육합',
        yukhapElement: '토',
        samhap: ['신', '자', '진'],
        samhapElement: '수',
        samhapWangji: '자',
        banghap: ['해', '자', '축'],
        banghapElement: '수',
        chung: '오',
        chungName: '자오충',
        samhyung: [],
        hyung: '묘',
        hyungName: '자묘형',
        pa: '유',
        paName: '자유파',
        hae: '미',
        haeName: '자미해',
    },
    축: {
        type: '묘지',
        yukhap: '자',
        yukhapName: '자축육합',
        yukhapElement: '토',
        samhap: ['사', '유', '축'],
        samhapElement: '금',
        samhapWangji: '유',
        banghap: ['해', '자', '축'],
        banghapElement: '수',
        chung: '미',
        chungName: '축미충',
        samhyung: ['축', '술', '미'],
        hyung: '',
        hyungName: '',
        pa: '진',
        paName: '축진파',
        hae: '오',
        haeName: '축오해',
    },
    인: {
        type: '생지',
        yukhap: '해',
        yukhapName: '인해육합',
        yukhapElement: '목',
        samhap: ['인', '오', '술'],
        samhapElement: '화',
        samhapWangji: '오',
        banghap: ['인', '묘', '진'],
        banghapElement: '목',
        chung: '신',
        chungName: '인신충',
        samhyung: ['인', '사', '신'],
        hyung: '',
        hyungName: '',
        pa: '해',
        paName: '인해파',
        hae: '사',
        haeName: '인사해',
    },
    묘: {
        type: '왕지',
        yukhap: '술',
        yukhapName: '묘술육합',
        yukhapElement: '화',
        samhap: ['해', '묘', '미'],
        samhapElement: '목',
        samhapWangji: '묘',
        banghap: ['인', '묘', '진'],
        banghapElement: '목',
        chung: '유',
        chungName: '묘유충',
        samhyung: [],
        hyung: '자',
        hyungName: '자묘형',
        pa: '오',
        paName: '묘오파',
        hae: '진',
        haeName: '묘진해',
    },
    진: {
        type: '묘지',
        yukhap: '유',
        yukhapName: '진유육합',
        yukhapElement: '금',
        samhap: ['신', '자', '진'],
        samhapElement: '수',
        samhapWangji: '자',
        banghap: ['인', '묘', '진'],
        banghapElement: '목',
        chung: '술',
        chungName: '진술충',
        samhyung: [],
        hyung: '진',
        hyungName: '진진자형',
        pa: '축',
        paName: '축진파',
        hae: '묘',
        haeName: '묘진해',
    },
    사: {
        type: '생지',
        yukhap: '신',
        yukhapName: '사신육합',
        yukhapElement: '수',
        samhap: ['사', '유', '축'],
        samhapElement: '금',
        samhapWangji: '유',
        banghap: ['사', '오', '미'],
        banghapElement: '화',
        chung: '해',
        chungName: '사해충',
        samhyung: ['인', '사', '신'],
        hyung: '',
        hyungName: '',
        pa: '신',
        paName: '신사파',
        hae: '인',
        haeName: '인사해',
    },
    오: {
        type: '왕지',
        yukhap: '미',
        yukhapName: '오미육합',
        yukhapElement: '화',
        samhap: ['인', '오', '술'],
        samhapElement: '화',
        samhapWangji: '오',
        banghap: ['사', '오', '미'],
        banghapElement: '화',
        chung: '자',
        chungName: '자오충',
        samhyung: [],
        hyung: '오',
        hyungName: '오오자형',
        pa: '묘',
        paName: '묘오파',
        hae: '축',
        haeName: '축오해',
    },
    미: {
        type: '묘지',
        yukhap: '오',
        yukhapName: '오미육합',
        yukhapElement: '화',
        samhap: ['해', '묘', '미'],
        samhapElement: '목',
        samhapWangji: '묘',
        banghap: ['사', '오', '미'],
        banghapElement: '화',
        chung: '축',
        chungName: '축미충',
        samhyung: ['축', '술', '미'],
        hyung: '',
        hyungName: '',
        pa: '술',
        paName: '술미파',
        hae: '자',
        haeName: '자미해',
    },
    신: {
        type: '생지',
        yukhap: '사',
        yukhapName: '사신육합',
        yukhapElement: '수',
        samhap: ['신', '자', '진'],
        samhapElement: '수',
        samhapWangji: '자',
        banghap: ['신', '유', '술'],
        banghapElement: '금',
        chung: '인',
        chungName: '인신충',
        samhyung: ['인', '사', '신'],
        hyung: '',
        hyungName: '',
        pa: '사',
        paName: '신사파',
        hae: '해',
        haeName: '신해해',
    },
    유: {
        type: '왕지',
        yukhap: '진',
        yukhapName: '진유육합',
        yukhapElement: '금',
        samhap: ['사', '유', '축'],
        samhapElement: '금',
        samhapWangji: '유',
        banghap: ['신', '유', '술'],
        banghapElement: '금',
        chung: '묘',
        chungName: '묘유충',
        samhyung: [],
        hyung: '유',
        hyungName: '유유자형',
        pa: '자',
        paName: '자유파',
        hae: '술',
        haeName: '유술해',
    },
    술: {
        type: '묘지',
        yukhap: '묘',
        yukhapName: '묘술육합',
        yukhapElement: '화',
        samhap: ['인', '오', '술'],
        samhapElement: '화',
        samhapWangji: '오',
        banghap: ['신', '유', '술'],
        banghapElement: '금',
        chung: '진',
        chungName: '진술충',
        samhyung: ['축', '술', '미'],
        hyung: '',
        hyungName: '',
        pa: '미',
        paName: '술미파',
        hae: '유',
        haeName: '유술해',
    },
    해: {
        type: '생지',
        yukhap: '인',
        yukhapName: '인해육합',
        yukhapElement: '목',
        samhap: ['해', '묘', '미'],
        samhapElement: '목',
        samhapWangji: '묘',
        banghap: ['해', '자', '축'],
        banghapElement: '수',
        chung: '사',
        chungName: '사해충',
        samhyung: [],
        hyung: '해',
        hyungName: '해해자형',
        pa: '인',
        paName: '인해파',
        hae: '신',
        haeName: '신해해',
    },
};
